### ISSUE TITLE
Full_path not working with <audio src=fullPath />

### ISSUE THREAD

**Issue by suhail339** [cocowalla/cordova-plugin-audiorecorder#3]
Hi, plugin is working fine on "android", and returning the full_path and filename when finished. Although i cannot make that path work with html5 audio element. 
I needed to upload file and preview for all previously stored files. How can i do that.

Sample full path returned : "/data/user/0/io.cordova.myapp12313/files/audioRecords/temps_41.m4a"

How can i use that path, help will be appreciated. Thanks for your time.

**Comment by cocowalla** [comment]
I'm sorry, but I don't think I understand the problem. Assuming the path you showed `/data/user/...` is what is returned on iOS, what is the problem with it?

**Comment by suhail339** [comment]
thanks for reply, /data/data/user/0/io.cordova.myapp12313/files/audioRecords/temps_41.m4a
is the path (on android) which is return, i only need to ask how can i make it work with html <audio > element, i cannot do that, may be i need to add "file://" with path to play recorded audio.

**Comment by cocowalla** [comment]
Ah OK, I get it now - you want to know how to play back an audio file that's been recorded with this plugin, given the full path that's returned, using an HTML audio control.

TBH, that's "out of scope" of this plugin, since it only handles recording, not playback.

To give you an idea though, you are going to need to resolve the full path to a file system URL. If you're using Ionic, you might do this using [`@ionic-native/File`](https://ionicframework.com/docs/native/file), which has a [`resolveLocalFilesystemUrl`](https://github.com/apache/cordova-plugin-file) method.

**Comment by suhail339** [comment]
Thanks i resolved the problem with mentioned "resolveLocalFileSystemUrl". Your effort is much appreciated.

**Comment by suhail339** [comment]
Forgive me for asking one last question, Is there any event which could indicate when recording is started by user, i mean after ".recordaudio", GUI opened but recording hasn't started, by any chance i can get any information how to listen to the event which actually fire on recording start? Thanks

**Comment by cocowalla** [comment]
I don't think so, no.

Here's roughly how I've used it before:

```typescript
let recorder = navigator["device"].audiorecorder;

// This Promise will only return when the audio recorder GUI ends
let resultStr = await new Promise<string>(function (resolve, reject) {
    recorder.recordAudio(result => resolve(result), error => reject(error),
60 * 60, "red", "black");
});

// Convert the result into an object
let result = JSON.parse(resultStr);

// Process the result (e.g. Upload the audio file, do something with
metadata etc)
await this.processAudioResult(result);
```

Cheers,

Colin
